# Generated by Django 6.1.1 on 2026-10-02 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelstation',
            name='rack_id',
        ),
        migrations.RemoveField(
            model_name='fuelstation',
            name='retail_price',
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='opis_truckstop_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_id', models.IntegerField()),
                ('retail_price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='routing.fuelstation')),
            ],
            options={
                'indexes': [models.Index(fields=['station'], name='routing_fue_station_26865e_idx')],
            },
        ),
    ]
