# Generated by Django 6.1.1 on 2026-10-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_remove_fuelstation_rack_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelprice',
            name='retail_price',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
