# Generated by Django 6.1.1 on 2026-10-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_alter_fuelprice_retail_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='geocoding_status',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['geocoding_status'], name='routing_fue_geocodi_6e90de_idx'),
        ),
    ]
