# Generated by Django 6.1.1 on 2026-10-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_fuelstation_geocoding_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='geocoding_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
