# Generated by Django 6.1.1 on 2026-10-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0005_fuelstation_geocoding_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
